### ISSUE TITLE
Replace CDVine with VineCopula

### ISSUE THREAD

**Issue by nanxstats** [elong0527/simuCCP#2]
Since CDVine is now archived on CRAN, and when loading the last installable version (1.4, released in 2015), it says:

```
> library(CDVine)
The CDVine package is no longer developed actively.
Please consider using the more general VineCopula package
(see https://CRAN.R-project.org/package=VineCopula),
which extends and improves the functionality of CDVine.
```

we should plan to migrate to VineCopula.

The imported functions from CDVine all have an apparent correspondence in VineCopula, except for `CDVineSim()`, therefore, it should be quite straightforward to migrate.

**Comment by elong0527** [comment]
I have included all required CDVine functions into simuCCP. All examples and vignettes can be run within this package. 

Please check and see if I can close this issue. Thanks!

**Comment by nanxstats** [comment]
@elong0527 I only see two issues via `R CMD check --as-cran` - looks like they have easy fixes, then we can close this:

```
File ‘simuCCP/libs/simuCCP.so’:
  Found no calls to: ‘R_registerRoutines’, ‘R_useDynamicSymbols’
It is good practice to register native routines and to disable symbol search.
```

```
Quitting from lines 26-28 (Introduction.Rmd)
Error: processing vignette 'Introduction.Rmd' failed with diagnostics:
'length(x) = 17 > 1' in coercion to 'logical(1)'

Quitting from lines 41-74 (simulation_cindex.Rmd)
Error: processing vignette 'simulation_cindex.Rmd' failed with diagnostics:
'length(x) = 17 > 1' in coercion to 'logical(1)'

SUMMARY: processing the following files failed:
  ‘Introduction.Rmd’ ‘simulation_cindex.Rmd’
```

**Comment by elong0527** [comment]
The issue for the `Rmd` files is weird. I can run it individually and also in [pkgdown website](https://elong0527.github.io/simuCCP/articles/simulation_cindex.html).

I guess it might be related to the compiling part.

The [github actions](https://github.com/elong0527/simuCCP/actions) check all passed with some Notes. I may keep it as is until we decided to submit it to CRAN.

**Comment by nanxstats** [comment]
Yes, it's strange that it didn't run under the `R CMD check` context but works fine under others. Agreed that it can be related to the compiled code. The current workaround to block the vignettes from being built looks good to me.

**Comment by nanxstats** [comment]
After https://github.com/elong0527/simuCCP/pull/4 is merged, this issue can be closed.
